name: ramaz
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.1.1+1

environment:
  sdk: ">=2.7.0 <=3.0.0"
 
dependencies:
  flutter:
    sdk: flutter
  # Firebase/Google
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  firebase_crashlytics: ^0.2.1+1
  firebase_messaging: ^7.0.3
  google_sign_in: ^4.5.1
  # Misc
  flutter_local_notifications: ^2.0.0
  idb_shim: ^1.12.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  url_launcher: ^5.2.5
  flutter_native_timezone: ^1.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test: 
    sdk: flutter
  matcher: any
  # pedantic: ^1.4.0
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: false  # overwrite
  ios: true  # overwrite 
  image_path: "images/logos/ramaz/icon.png"  # path to the logo
  # Or, alternatively:
  # image_path_android
  # image_path_ios

  # We don't need a backgroun b/c we have a full image
  # adaptive_icon_background
  # adaptive_icon_foreground: "images/ramaz_words.png"
  # adaptive_icon_background: "images/blue.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icons/baseball.png
    - images/icons/basketball.png
    - images/icons/hockey.png
    - images/icons/soccer.png
    - images/icons/tennis.png
    - images/icons/volleyball.png
    - images/logos/drive.png
    - images/logos/google.png
    - images/logos/google_sign_in.png
    - images/logos/outlook.jpg
    - images/logos/schoology.png
    - images/logos/senior_systems.png
    - images/logos/ramaz/ram_rectangle.png
    - images/logos/ramaz/ram_square_words.png
    - images/logos/ramaz/ram_square.png
    - images/logos/ramaz/teal.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
