name: Analyzer

on: pull_request

jobs: 
  analyze: 
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./repo

    steps: 
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v2
        with: 
          path: flutter/
          key: ${{ runner.os }}-flutter

      - name: Install Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: britannio/action-install-flutter@v1.0

      - name: Add Flutter to path
        run: |
          pwd
          echo "../flutter/bin" >> $GITHUB_PATH
        
      - uses: actions/checkout@v2
        with: 
          path: repo  # keeps Flutter separate from repo

      - name: Analyze
        run: flutter analyze --dartdocs
